import Head from 'next/head'
import Form from './components/Form'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Email Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-[100vh] w-[100vw] flex flex-col justify-center'>
        <Form />
      </main>

      <footer>

      </footer>
    </div >
  )
}
