import Head from 'next/head'
import Footer from './components/Footer'
import EmailForm from './components/EmailForm'
import Navbar from './components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Email Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className='h-[100vh] w-[100vw] flex flex-col justify-center'>
        <EmailForm />
      </main>

      <Footer />
    </div >
  )
}
